# Site settings
title: SeBit
email: 
description: > # this means to ignore newlines until "baseurl:"
  Bits of IT by Sebastian.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://banescusebi.github.io" # the base hostname & protocol for your site
twitter_username: banescusebi
github_username:  banescusebi

# Build settings
markdown: kramdown
